version: '3'
services:
  app:
    build: .
    container_name: php-app
    ports:
      - "3000:80" # Cổng 8080 ngoài host sẽ map tới cổng 80 của Apache trong container
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # Expose cổng MySQL để có thể kết nối từ bên ngoài nếu cần
